### ISSUE TITLE
A6600 fw v1.10 and rx10m4 fw v2.00 pair but then show as never connected in the app

### ISSUE THREAD

**Issue by codyps** [Staacks/alpharemote#2]
On my Sony a6600 with firmware v1.10, after resetting its networking, reenabling Bluetooth, reenabling the Bluetooth remote control, and entering the pairing screen on the a6600: pairing works through the app, and the app reports having a camera paired but shows ’"unknown" is offline.’ in the app settings view, and no controls appear.

The same occurs for my Sony rx10m4, though that camera lacks an option to enable the Bluetooth remote control, and might not support that control mechanism. I have a Sony Bluetooth remote control that I'll try with it later.

All this was using my Google pixel 8pro with Android 14 build  AP2A.240905.003.B1

Let me know if there's additional info I can capture to help.

**Comment by Staacks** [comment]
Hm... You pretty much listed everything that I would have suggested to try, so this one might be trickier. I will try a few things with my a6400. So far I always had the impression that it is not too different from my a6400.

Btw, if you are doing the Android 15, please test this before and after the update to rule out issues with Android 14. I have developed most of the app on 14 and only updated when the app was almost done, but I cannot simply go back to 14 to try it and I cannot rule out entirely that there might be a relevant difference here (even though I would not expect it).

**Comment by Staacks** [comment]
I just published version 0.17 on the Google Play public test branch (might take an hour until your Play Store sees the update). I think it should resolve the issue. Could you please try it?

**Comment by Staacks** [comment]
I will close this issue now as I think it was resolved with version 0.17 - at least the initial connection after pairing. The other part - not being able to connect later as you also described it in other issues - seems to be the same issue as #4. I will try and collect these relating issues over there to keep an overview of what remains a problem.

(Feel free to reopen if you think this here is something different.)
