### ISSUE TITLE
Focus control an A7R III not working

### ISSUE THREAD

**Issue by dregele** [Staacks/alpharemote#7]
Great app, thanks for the effort. Tested with an A7R3 and a Pixel 8 Pro, and everything works beautifully except manual control of the focus drive. Camera and lens are set to MF and focus can be changed by using the focus wheel on the lens, but the focus buttons in the app do nothing.

**Comment by Staacks** [comment]
Could it be that you have to set the lens to AF and the camera to MF? My puny APS-C lenses do not have an MF switch, but I think that the MF switch on the lens actually switches between focus by ring and focus by motor, by which I mean that the lens has no idea whether the camera is "logically" using autofocus or not, it will simply not allow any focus adjustments via motor from the camera regardless of whether it is coming from AF or a remote.

If that's it, I should add it to the FAQ as this is one of those typical things that are beyond the app's control and extremely unintuitive. (Although it is reasonable from a technical point of view as the lenses probably have to physically disconnect the focus motor to allow using the focus ring instead.)

**Comment by dregele** [comment]
Thanks for the reply! I will systematically try out all the different combinations and maybe a lens without an AF/MF toggle. The lenses are all focus-by-wire, so the signal from the focus ring is transmitted electronically, i.e. no mechanical connection ring-lens.

The only other apps I managed to get to control the focus drive were Helicon Remote and Monitor+, but only if connected via USB.

**Comment by dregele** [comment]
Ok, so I tested all lenses I could get my hands on.

Sigma 28-70, dedicated AF/MF switch: Switch on lens needs to be on AF, camera on MF - works
Tamron 50-400, programmable switches: Camera in MF - works.
Samyang 45: no switch, does not work. DMF does not work either.

So you were right and the lens needs to be in a state where it accepts focus input from the camera. Maybe worth mentioning that the Tamron is on the latest firmware, while the other two are still on the factory one.

**Comment by Staacks** [comment]
Ok, except for the Samyang that's what I would have expected. I think the MF buttons at the lens are generally more a "motor off" button than just a conveniently placed copy of the MF setting of the camera. I am not sure if the camera even knows if the ring on the lens is driving the focus electronically. I would not be surprised if the camera only knows that the lens is set to MF and then it does not even try to drive it - but I could be wrong about that - especially as I do not own a lens with a MF switch.

About that Samyang lens:
I am wondering if there is something to improve in the app after all. In the end it just sends simple button presses, but there is something special about the controls for zoom and focus as there is an additional parameter which seems to define how fast the lens should travel. At least that's what others documented when experimenting with these Bluetooth commands. On the lenses that I tested this parameter did little or nothing and the overall reaction to the focus butons also seemed to depend on the lens model. So, I kept the focus and zoom buttons on the remote on what I thought should be a "medium" setting. Now I am wondering if maybe maximum or minimum should be the default and if maybe the Samyang lens only reacts to that setting.

If you would like to try: In settings under the "custom buttons" section you can add focus far/near buttons. Here you can also set the preferred speed for that button. Could you test if your Samyang lens does anything if you set the speed to maximum or minimum? (This setting does not affect the default remote control buttons under "Camera", but the ones that appear in the notification area and at the bottom of the "camera" page.)

**Comment by dregele** [comment]
I just tried with different speed, but no change. The command is transmitted (range indicator comes up) but no focus change. This seems to be a problem with Samyang lenses, see https://www.dpreview.com/forums/thread/4635591?page=2

Still a very nice and useful app, thanks!

**Comment by Staacks** [comment]
ok, thanks for testing. I will add your findings to the FAQ.
